apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profile-config
data:
  MYSQL_DB_HOST: '{{ .Values.profile.mysql.host }}'
  # TODO: update MYSQL_DB_USER and MYSQL_DB_PASSWORD to match the variables that you used
  #       to install the MySQL service
  MYSQL_DB_USER: '{{ .Values.profile.mysql.user }}'
  MYSQL_DB_PASSWORD: '{{ .Values.profile.mysql.password }}'
  MYSQL_DB_PORT: '{{ .Values.profile.mysql.port }}'
