# TODO: Implement the deployment configuration for the chat service
{{- if eq .Values.global.environment "gcp" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chat.releaseName }}-deployment
spec:
  replicas: {{ .Values.chat.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.chat.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.chat.releaseName }}
    spec:
      containers:
        - name: {{ .Values.chat.image }}
          image: {{ .Values.chat.prefix }}/{{ .Values.chat.image }}:{{ .Values.chat.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.chat.hpa.cpuRequest }}
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-chat-config
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-chat-config
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-chat-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-chat-config
                  key: MYSQL_DB_PORT

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.chat.releaseName }}-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.chat.releaseName }}-deployment
  minReplicas: {{ .Values.chat.hpa.minReplicas }}
  maxReplicas: {{ .Values.chat.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.chat.hpa.targetCPUUtilizationPercentage }}
{{- end }}