apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.profile.releaseName }}-deployment
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.profile.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.profile.releaseName }}
    spec:
      containers:
        - name: {{ .Values.profile.image }}
          image: {{ .Values.profile.prefix }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.profile.hpa.cpuRequest }}
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_PORT

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.profile.releaseName }}-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.profile.releaseName }}-deployment
  minReplicas: {{ .Values.profile.hpa.minReplicas }}
  maxReplicas: {{ .Values.profile.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.profile.hpa.targetCPUUtilizationPercentage }}