# TODO: Implement the deployment configuration for the login service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.login.releaseName }}-deployment
spec:
  replicas: {{ .Values.login.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.login.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.login.releaseName }}
    spec:
      containers:
        - name: {{ .Values.login.image }}
          image: {{ .Values.login.prefix }}/{{ .Values.login.image }}:{{ .Values.login.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.login.hpa.cpuRequest }}
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_PORT
            - name: CHAT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: CHAT_ENDPOINT

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.login.releaseName }}-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.login.releaseName }}-deployment
  minReplicas: {{ .Values.login.hpa.minReplicas }}
  maxReplicas: {{ .Values.login.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.login.hpa.targetCPUUtilizationPercentage }}
